### ISSUE TITLE
Crash when split terminals on Ubuntu 16.04

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#11]
Okay I have Arch too! Hope I can make it work there :p

Ubuntu 16.04
DMD    2.069.2
DUB    0.9.24

(gdb) r
Starting program: /usr/bin/terminix 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffead58700 (LWP 12815)]
[New Thread 0x7fffea557700 (LWP 12816)]

** (terminix:12811): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-rnEVbcNV3H: Connection refused
[New Thread 0x7fffe3fff700 (LWP 12817)]

(terminix:12811): GLib-CRITICAL **: g_variant_get_int64: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT64)' failed
[New Thread 0x7fffd7fff700 (LWP 12869)]
[New Thread 0x7fffd77fe700 (LWP 12870)]
[Thread 0x7fffd7fff700 (LWP 12869) exited]

(terminix:12811): GLib-CRITICAL **: g_variant_get_int64: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT64)' failed
[Thread 0x7fffd77fe700 (LWP 12870) exited]

(terminix:12811): GLib-CRITICAL **: g_variant_get_int64: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT64)' failed

(terminix:12811): Gtk-CRITICAL **: gtk_window_get_default_widget: assertion 'GTK_IS_WINDOW (window)' failed

(terminix:12811): Gtk-CRITICAL **: gtk_window_set_default: assertion 'GTK_IS_WINDOW (window)' failed

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4b5ff55 in has_case_prefix (haystack=haystack@entry=0x0, needle=needle@entry=0x7ffff4bc8594 "file:/") at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./glib/gconvert.c:1267
1267	/build/glib2.0-IfQpAv/glib2.0-2.47.3/./glib/gconvert.c: No such file or directory.

(gdb) bt full
#0  0x00007ffff4b5ff55 in has_case_prefix (haystack=haystack@entry=0x0, needle=needle@entry=0x7ffff4bc8594 "file:/") at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./glib/gconvert.c:1267
        h = 0x0
        n = 0x7fffffffb7e0 ""
#1  0x00007ffff4b61382 in g_filename_from_uri (uri=0x0, hostname=0x7fffffffb7e0, error=0x7fffffffb7e8) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./glib/gconvert.c:1564
        path_part = <optimized out>
        host_part = <optimized out>
        unescaped_hostname = <optimized out>
        result = <optimized out>
        filename = <optimized out>
        offs = <optimized out>
#2  0x0000000000848077 in glib.URI.URI.filenameFromUri(immutable(char)[], out immutable(char)[]) ()
#3  0x00000000007f8f11 in gx.terminix.terminal.terminal.Terminal.currentDirectory() ()
#4  0x00000000007f066d in gx.terminix.session.Session.onTerminalRequestSplit(gx.terminix.terminal.terminal.Terminal, gtkc.gtktypes.GtkOrientation) ()
#5  0x00000000007f6252 in gx.terminix.terminal.terminal.Terminal.notifyTerminalRequestSplit(gtkc.gtktypes.GtkOrientation) ()
#6  0x00000000007f4f4e in gx.terminix.terminal.terminal.Terminal.createActions(gio.SimpleActionGroup.SimpleActionGroup).__dgliteral2!(glib.Variant.Variant, gio.SimpleAction.SimpleAction).__dgliteral2(glib.Variant.Variant, gio.SimpleAction.SimpleAction) ()
#7  0x000000000083929c in gio.SimpleAction.SimpleAction.callBackActivate(gtkc.giotypes.GSimpleAction*, gtkc.glibtypes.GVariant*, gio.SimpleAction.SimpleAction) ()
#11 0x00007ffff449b0bf in <emit signal ??? on instance 0x1126b70 [GSimpleAction]> (instance=instance@entry=0x1126b70, signal_id=<optimized out>, detail=detail@entry=0) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3441
        var_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffbdf0, reg_save_area = 0x7fffffffbd30}}
    #8  0x00007ffff447ffa5 in g_closure_invoke (closure=0x7ffff7f4b000, return_value=return_value@entry=0x0, n_param_values=2, param_values=param_values@entry=0x7fffffffbb50, invocation_hint=invocation_hint@entry=0x7fffffffbad0)
    at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gclosure.c:804
                marshal = <optimized out>
                marshal_data = <optimized out>
                in_marshal = 0
                real_closure = 0x7ffff7f4afe0
                __func__ = "g_closure_invoke"
    #9  0x00007ffff4491ff1 in signal_emit_unlocked_R (node=node@entry=0xf3c880, detail=detail@entry=0, instance=instance@entry=0x1126b70, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffbb50) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3629
                tmp = <optimized out>
                handler = 0x1195780
                accumulator = 0x0
                emission = {next = 0x7fffffffc0d0, instance = 0x1126b70, ihint = {signal_id = 217, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 4}
                handler_list = 0x1195780
                return_accu = 0x0
                accu = 
                      {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                signal_id = 217
                max_sequential_handler_number = 4251
                return_value_altered = 0
    #10 0x00007ffff449ad8c in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffbd10) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3385
                instance_and_params = 0x7fffffffbb50
                signal_return_type = <optimized out>
                param_values = 0x7fffffffbb68
                i = <optimized out>
                n_params = <optimized out>
                __func__ = "g_signal_emit_valist"
#12 0x00007ffff3d75555 in g_simple_action_activate (action=0x1126b70, parameter=0x0) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gio/gsimpleaction.c:225
        simple = 0x1126b70 [GSimpleAction]
        __func__ = "g_simple_action_activate"
#13 0x00007fffee99bb8e in gtk_action_muxer_activate_action (action_group=0x1189580, action_name=0x1071861 "terminal.split-horizontal", parameter=0x0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkactionmuxer.c:412
        muxer = 0x1189580 [GtkActionMuxer]
        group = <optimized out>
        unprefixed_name = 0x107186a "split-horizontal"
#14 0x00007fffee99bbc4 in gtk_action_muxer_activate_action (action_group=0x1090c80, action_name=0x1071861 "terminal.split-horizontal", parameter=0x0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkactionmuxer.c:414
        parameter = 0x0
        action_name = 0x1071861 "terminal.split-horizontal"
---Type <return> to continue, or q <return> to quit---
        action_group = 0x1090c80
        muxer = 0x1090c80 [GtkActionMuxer]
        group = <optimized out>
        unprefixed_name = 0x107186a "split-horizontal"
#15 0x00007fffee99bbc4 in gtk_action_muxer_activate_action (action_group=0x1083380, action_name=0x1071861 "terminal.split-horizontal", parameter=0x0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkactionmuxer.c:414
        parameter = 0x0
        action_name = 0x1071861 "terminal.split-horizontal"
        action_group = 0x1083380
        muxer = 0x1083380 [GtkActionMuxer]
        group = <optimized out>
        unprefixed_name = 0x107186a "split-horizontal"
#16 0x00007fffee99bbc4 in gtk_action_muxer_activate_action (action_group=0xfe6400, action_name=0x1071861 "terminal.split-horizontal", parameter=0x0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkactionmuxer.c:414
        parameter = 0x0
        action_name = 0x1071861 "terminal.split-horizontal"
        action_group = 0xfe6400
        muxer = 0xfe6400 [GtkActionMuxer]
        group = <optimized out>
        unprefixed_name = 0x107186a "split-horizontal"
#17 0x00007fffee99bbc4 in gtk_action_muxer_activate_action (action_group=0x1038380, action_name=0x1071861 "terminal.split-horizontal", parameter=0x0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkactionmuxer.c:414
        parameter = 0x0
        action_name = 0x1071861 "terminal.split-horizontal"
        action_group = 0x1038380
        muxer = 0x1038380 [GtkActionMuxer]
        group = <optimized out>
        unprefixed_name = 0x107186a "split-horizontal"
#18 0x00007fffee99bbc4 in gtk_action_muxer_activate_action (action_group=0x1038340, action_name=0x1071861 "terminal.split-horizontal", parameter=0x0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkactionmuxer.c:414
        parameter = 0x0
        action_name = 0x1071861 "terminal.split-horizontal"
        action_group = 0x1038340
        muxer = 0x1038340 [GtkActionMuxer]
        group = <optimized out>
        unprefixed_name = 0x107186a "split-horizontal"
#19 0x00007fffee99bbc4 in gtk_action_muxer_activate_action (action_group=0x1038300, action_name=0x1071861 "terminal.split-horizontal", parameter=0x0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkactionmuxer.c:414
        parameter = 0x0
        action_name = 0x1071861 "terminal.split-horizontal"
        action_group = 0x1038300
        muxer = 0x1038300 [GtkActionMuxer]
        group = <optimized out>
        unprefixed_name = 0x107186a "split-horizontal"
#20 0x00007fffeeae0996 in gtk_menu_tracker_item_activated (self=0x107ee00 [GtkMenuTrackerItem]) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkmenutrackeritem.c:804
        action_name = 0x1071861 "terminal.split-horizontal"
        action_target = 0x0
        __func__ = "gtk_menu_tracker_item_activated"
#21 0x00007fffeeadb303 in gtk_popover_item_activate (button=<optimized out>, user_data=0x107ee00) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkmenusectionbox.c:184
        item = 0x107ee00 [GtkMenuTrackerItem]
        popover = 0x119a1b0 [GtkPopover]
#25 0x00007ffff449b0bf in <emit signal ??? on instance 0x11a0210 [GtkModelButton]> (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3441
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffffffc3f0, reg_save_area = 0x7fffffffc330}}
    #22 0x00007ffff447ffa5 in g_closure_invoke (closure=0x10ec630, return_value=return_value@entry=0x0, n_param_values=1, param_values=param_values@entry=0x7fffffffc160, invocation_hint=invocation_hint@entry=0x7fffffffc0e0)
    at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gclosure.c:804
                marshal = <optimized out>
                marshal_data = <optimized out>
                in_marshal = 0
                real_closure = 0x10ec610
                __func__ = "g_closure_invoke"
    #23 0x00007ffff4491ff1 in signal_emit_unlocked_R (node=node@entry=0xf2f390, detail=detail@entry=0, instance=instance@entry=0x11a0210, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffc160) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3629
---Type <return> to continue, or q <return> to quit---
                tmp = <optimized out>
                handler = 0x1083100
                accumulator = 0x0
                emission = {next = 0x7fffffffc580, instance = 0x11a0210, ihint = {signal_id = 183, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 4}
                handler_list = 0x1083100
                return_accu = 0x0
                accu = 
                      {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                signal_id = 183
                max_sequential_handler_number = 4249
                return_value_altered = 1
    #24 0x00007ffff449ad8c in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffc310) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3385
                instance_and_params = 0x7fffffffc160
                signal_return_type = <optimized out>
                param_values = 0x7fffffffc178
                i = <optimized out>
                n_params = <optimized out>
                __func__ = "g_signal_emit_valist"
#26 0x00007fffee9cd54d in gtk_button_do_release (button=0x11a0210 [GtkModelButton], emit_clicked=<optimized out>) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkbutton.c:1899
        emit_clicked = <optimized out>
        button = 0x11a0210 [GtkModelButton]
        priv = <optimized out>
#27 0x00007fffee9cd5b5 in gtk_real_button_released (button=0x11a0210 [GtkModelButton]) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkbutton.c:2017
#31 0x00007ffff449b0bf in <emit signal ??? on instance 0x11a0210 [GtkModelButton]> (instance=instance@entry=0x11a0210, signal_id=<optimized out>, detail=detail@entry=0) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3441
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffffffc8a0, reg_save_area = 0x7fffffffc7e0}}
    #28 0x00007ffff447ffa5 in g_closure_invoke (closure=closure@entry=0xf39040, return_value=return_value@entry=0x0, n_param_values=1, param_values=param_values@entry=0x7fffffffc610, invocation_hint=invocation_hint@entry=0x7fffffffc590)
    at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gclosure.c:804
                marshal = <optimized out>
                marshal_data = <optimized out>
                in_marshal = 0
                real_closure = 0xf39020
                __func__ = "g_closure_invoke"
    #29 0x00007ffff4491b2c in signal_emit_unlocked_R (node=node@entry=0xf8c680, detail=detail@entry=0, instance=instance@entry=0x11a0210, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffc610) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3559
                accumulator = 0x0
                emission = {next = 0x7fffffffcca0, instance = 0x11a0210, ihint = {signal_id = 182, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 15995488}
                handler_list = <optimized out>
                return_accu = 0x0
                accu = 
                      {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                signal_id = 182
                max_sequential_handler_number = 4249
                return_value_altered = <optimized out>
    #30 0x00007ffff449ad8c in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffc7c0) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3385
                instance_and_params = 0x7fffffffc610
                signal_return_type = <optimized out>
                param_values = 0x7fffffffc628
                i = <optimized out>
                n_params = <optimized out>
                __func__ = "g_signal_emit_valist"
#32 0x00007fffee9cb640 in multipress_released_cb (gesture=0x1051f90 [GtkGestureMultiPress], n_press=<optimized out>, x=<optimized out>, y=<optimized out>, widget=0x11a0210 [GtkModelButton])
    at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkbutton.c:613
        button = 0x11a0210 [GtkModelButton]
        priv = 0x11a00b0
        sequence = <optimized out>
---Type <return> to continue, or q <return> to quit---
#33 0x00007ffff426de40 in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#34 0x00007ffff426d8ab in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#35 0x00007ffff4480cf5 in g_cclosure_marshal_generic_va (closure=0xfdd950, return_value=0x0, instance=0x1051f90, args_list=<optimized out>, marshal_data=0x0, n_params=3, param_types=0xf71350)
    at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gclosure.c:1604
        rtype = 0x7ffff426e230 <ffi_type_void>
        rvalue = 0x7fffffffca60
        n_args = 5
        atypes = 0x7fffffffca20
        args = 0x7fffffffc9e0
        storage = 0x7fffffffc9b0
        i = <optimized out>
        cif = {abi = FFI_UNIX64, nargs = 5, arg_types = 0x7fffffffca20, rtype = 0x7ffff426e230 <ffi_type_void>, bytes = 0, flags = 2048}
        cc = 0xfdd950
        enum_tmpval = <optimized out>
        tmpval_used = 0
        args_copy = {{gp_offset = 32, fp_offset = 80, overflow_arg_area = 0x7fffffffce80, reg_save_area = 0x7fffffffcdc0}}
#36 0x00007ffff44801d4 in _g_closure_invoke_va (closure=closure@entry=0xfdd950, return_value=return_value@entry=0x0, instance=instance@entry=0x1051f90, args=args@entry=0x7fffffffcda0, n_params=<optimized out>, param_types=0xf71350)
    at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gclosure.c:867
        marshal = <optimized out>
        marshal_data = <optimized out>
        in_marshal = 0
        real_closure = 0xfdd930
        __func__ = "_g_closure_invoke_va"
#37 0x00007ffff449a9d6 in g_signal_emit_valist (instance=0x1051f90, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffcda0) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3294
        return_accu = <optimized out>
        accu = 
              {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x0
        emission = {next = 0x7fffffffd030, instance = 0x1051f90, ihint = {signal_id = 231, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 15863904}
        signal_id = 231
        instance_type = <optimized out>
        emission_return = 
              {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 4
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        l = <optimized out>
        fastpath = <optimized out>
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#38 0x00007ffff449b0bf in g_signal_emit (instance=instance@entry=0x1051f90, signal_id=<optimized out>, detail=detail@entry=0) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3441
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffffffce80, reg_save_area = 0x7fffffffcdc0}}
#39 0x00007fffeea798f1 in gtk_gesture_multi_press_end (gesture=0x1051f90 [GtkGestureMultiPress], sequence=<optimized out>) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkgesturemultipress.c:273
        multi_press = 0x1051f90 [GtkGestureMultiPress]
        current = <optimized out>
        x = 38
        y = 12
#40 0x00007ffff4482dbe in g_cclosure_marshal_VOID__BOXEDv (closure=0xf53640, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0xf53670)
    at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gmarshal.c:1950
---Type <return> to continue, or q <return> to quit---
        cc = 0xf53640
        data1 = <optimized out>
        data2 = <optimized out>
        callback = <optimized out>
        arg0 = 0x0
        args_copy = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffd210, reg_save_area = 0x7fffffffd150}}
#41 0x00007ffff44801d4 in _g_closure_invoke_va (closure=closure@entry=0xf53640, return_value=return_value@entry=0x0, instance=instance@entry=0x1051f90, args=args@entry=0x7fffffffd130, n_params=<optimized out>, param_types=0xf53670)
    at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gclosure.c:867
        marshal = <optimized out>
        marshal_data = <optimized out>
        in_marshal = 0
        real_closure = 0xf53620
        __func__ = "_g_closure_invoke_va"
#42 0x00007ffff449a9d6 in g_signal_emit_valist (instance=0x1051f90, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd130) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3294
        return_accu = <optimized out>
        accu = 
              {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x0
        emission = {next = 0x7fffffffd490, instance = 0x1051f90, ihint = {signal_id = 226, detail = 0, run_type = G_SIGNAL_RUN_LAST}, state = EMISSION_RUN, chain_type = 15863904}
        signal_id = 226
        instance_type = <optimized out>
        emission_return = 
              {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 4
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        l = <optimized out>
        fastpath = <optimized out>
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#43 0x00007ffff449b0bf in g_signal_emit (instance=instance@entry=0x1051f90, signal_id=<optimized out>, detail=detail@entry=0) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3441
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffffffd210, reg_save_area = 0x7fffffffd150}}
#44 0x00007fffeea76c4e in _gtk_gesture_check_recognized (sequence=0x0, recognized=0, gesture=0x1051f90 [GtkGestureMultiPress]) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkgesture.c:345
        has_matching_touchpoints = <optimized out>
#45 0x00007fffeea76c4e in _gtk_gesture_check_recognized (gesture=gesture@entry=0x1051f90 [GtkGestureMultiPress], sequence=sequence@entry=0x0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkgesture.c:386
        has_matching_touchpoints = <optimized out>
#46 0x00007fffeea78273 in gtk_gesture_handle_event (controller=0x1051f90 [GtkGestureMultiPress], event=0x11039d0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkgesture.c:777
        gesture = 0x1051f90 [GtkGestureMultiPress]
        sequence = 0x0
        source_device = <optimized out>
        was_recognized = 1
#47 0x00007fffeea7ae45 in gtk_gesture_single_handle_event (controller=0x1051f90 [GtkGestureMultiPress], event=0x11039d0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkgesturesingle.c:221
        sequence = 0x0
        source_device = <optimized out>
        source = GDK_SOURCE_MOUSE
        button = 1
        i = <optimized out>
        retval = <optimized out>
        test_touchscreen = <optimized out>
---Type <return> to continue, or q <return> to quit---
#48 0x00007fffeea4ab6b in gtk_event_controller_handle_event (controller=0x1051f90 [GtkGestureMultiPress], event=event@entry=0x11039d0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkeventcontroller.c:230
        controller_class = 0xf9a600
        retval = 0
        __func__ = "gtk_event_controller_handle_event"
#49 0x00007fffeebfbacb in _gtk_widget_run_controllers (widget=0x11a0210 [GtkModelButton], event=0x11039d0, phase=GTK_PHASE_BUBBLE) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkwidget.c:7321
        controller_phase = <optimized out>
Python Exception <class 'TypeError'> iter() returned non-iterator of type '_iterator': 
        next = 0x0
        data = 0x107b170
        handled = 0
        priv = 0x11a0140
        l = <optimized out>
#50 0x00007fffeeabfeba in _gtk_marshal_BOOLEAN__BOXEDv (closure=0xe81290, return_value=0x7fffffffd4c0, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0xe7d720)
    at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkmarshalers.c:131
        cc = <optimized out>
        data1 = <optimized out>
        data2 = <optimized out>
        callback = <optimized out>
        arg0 = 0x11039d0
        args_copy = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffd670, reg_save_area = 0x7fffffffd5b0}}
        v_return = <optimized out>
        __func__ = "_gtk_marshal_BOOLEAN__BOXEDv"
#51 0x00007ffff44801d4 in _g_closure_invoke_va (closure=closure@entry=0xe81290, return_value=return_value@entry=0x7fffffffd4c0, instance=instance@entry=0x11a0210, args=args@entry=0x7fffffffd590, n_params=<optimized out>, param_types=0xe7d720) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gclosure.c:867
        marshal = <optimized out>
        marshal_data = <optimized out>
        in_marshal = 0
        real_closure = 0xe81270
        __func__ = "_g_closure_invoke_va"
#52 0x00007ffff449a4e8 in g_signal_emit_valist (instance=0x11a0210, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd590) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3294
        return_accu = <optimized out>
        accu = 
              {g_type = 20, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0xe7d740
        emission = {next = 0x0, instance = 0x11a0210, ihint = {signal_id = 67, detail = 0, run_type = G_SIGNAL_RUN_LAST}, state = EMISSION_RUN, chain_type = 15995488}
        signal_id = 67
        instance_type = <optimized out>
        emission_return = 
              {g_type = 20, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 20
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        l = <optimized out>
        fastpath = <optimized out>
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#53 0x00007ffff449b0bf in g_signal_emit (instance=instance@entry=0x11a0210, signal_id=<optimized out>, detail=detail@entry=0) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gobject/gsignal.c:3441
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffffffd670, reg_save_area = 0x7fffffffd5b0}}
#54 0x00007fffeebfdb0c in gtk_widget_event_internal (widget=0x11a0210 [GtkModelButton], event=0x11039d0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkwidget.c:7692
        signal_num = <optimized out>
---Type <return> to continue, or q <return> to quit---
        return_val = 0
        handled = 0
        event = 0x11039d0
        widget = 0x11a0210 [GtkModelButton]
#55 0x00007fffeeabd1de in propagate_event (topmost=<optimized out>, event=<optimized out>, widget=0x11a0210 [GtkModelButton]) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkmain.c:2527
        tmp = <optimized out>
        handled_event = <optimized out>
        handled_event = 0
#56 0x00007fffeeabd1de in propagate_event (widget=<optimized out>, event=0x11039d0, captured=<optimized out>, topmost=0x0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkmain.c:2629
        handled_event = 0
#57 0x00007fffeeabefdc in gtk_main_do_event (event=0x11039d0) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gtk/gtkmain.c:1850
        event_widget = <optimized out>
        grab_widget = 0x11a0210 [GtkModelButton]
        topmost_widget = <optimized out>
        window_group = 0xf0f070 [GtkWindowGroup]
        rewritten_event = <optimized out>
        device = 0xe125a0 [GdkX11DeviceXI2]
        tmp_list = <optimized out>
        __func__ = "gtk_main_do_event"
#58 0x00007ffff36057f2 in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at /build/gtk+3.0-vke6KI/gtk+3.0-3.18.6/./gdk/x11/gdkeventsource.c:364
        display = <optimized out>
        event = <optimized out>
#59 0x00007ffff4b7e117 in g_main_context_dispatch (context=0xe10360) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./glib/gmain.c:3154
        dispatch = 0x7ffff36057d0 <gdk_event_source_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = <optimized out>
        cb_data = <optimized out>
        need_destroy = <optimized out>
        source = 0xe49830
        current = 0xe28600
        i = 0
#60 0x00007ffff4b7e117 in g_main_context_dispatch (context=context@entry=0xe10360) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./glib/gmain.c:3769
#61 0x00007ffff4b7e370 in g_main_context_iterate (context=context@entry=0xe10360, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./glib/gmain.c:3840
        max_priority = 2147483647
        timeout = 358
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 4
        fds = 0x10ec930
#62 0x00007ffff4b7e41c in g_main_context_iteration (context=0xe10360, context@entry=0x0, may_block=may_block@entry=1) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./glib/gmain.c:3901
        retval = <optimized out>
#63 0x00007ffff3d6d5ec in g_application_run (application=0xe151a0 [GtkApplication], argc=0, argv=0x0) at /build/glib2.0-IfQpAv/glib2.0-2.47.3/./gio/gapplication.c:2311
        arguments = 0xdf4880
        status = 0
        __func__ = "g_application_run"
#64 0x0000000000819dfc in gio.Application.Application.run(immutable(char)[][]) ()
#65 0x00000000007bd286 in D main ()
(gdb)

**Comment by alex285** [comment]
hmm, did you read bellow? It is on Ubuntu 16.04 :)

**Comment by gnunn1** [comment]
Oops sorry about that, just saw you referenced this one in your other one and leapt to the conclusion it was related. I'll have a look at this in the next day or two as I'll have to setup another VM.

**Comment by gnunn1** [comment]
I see Ubuntu 16.04 is not released, is it using GTK 3.19 as well?

**Comment by alex285** [comment]
@gnunn1 No it is Gtk 3.18.6 
It is shown on debug, thats why I didn't refer versions. Basically you can get Gtk 3.18 in Ubuntu 15.10 too with PPAs. For example guys that run Ubuntu Gnome are more likely to do that.

**Comment by gnunn1** [comment]
Ok thanks for taking the time to run GDB, looks like the issue is when it is getting the directory of the current terminal to apply to the new one. VTE gives you the current directory as a URI which needs to be converted and this is what I see in frames 2 and 3. Not sure why it's failing on the conversion but could be I'm passing something bad to the GLib function, I'll try to reproduce it and see what is up.

**Comment by brittyazel** [comment]
I think I am getting the same issue, except I am on Archlinux x64. This is my error:

(terminix:10749): GLib-CRITICAL **: g_variant_get_int64: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT64)' failed

(terminix:10749): GLib-CRITICAL **: g_variant_get_int64: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT64)' failed

(terminix:10749): Gtk-CRITICAL **: gtk_window_get_default_widget: assertion 'GTK_IS_WINDOW (window)' failed

(terminix:10749): Gtk-CRITICAL **: gtk_window_set_default: assertion 'GTK_IS_WINDOW (window)' failed
Segmentation fault (core dumped)

**Comment by gnunn1** [comment]
Fixed the problem in Ubuntu 16.04, I was requesting an Int64 from GSettings instead of a Int32, hard to believe this was the problem but now it is working fine in my VM. I uploaded an Ubuntu test release in git releases, if you have some time please give it a try and confirm that problem is resolved.

Note that in this version transparency is temporarily disabled due to artifacts in Ubuntu, damn CSD/Mutter versus Ambiance :(

**Comment by brittyazel** [comment]
Version 0.32 is still crashing the exact same way for me. Also, transparency was still very much enabled and working on the latest version.

**Comment by alex285** [comment]
+1
works on Ubuntu now! Thanks!

**Comment by gnunn1** [comment]
Thanks for the confirmation, closing.
