### ISSUE TITLE
new session should open in current working directory

### ISSUE THREAD

**Issue by giray** [gnunn1/terminix#246]
When I split the session, or open a new tab I expect that the new session starts in the 
current working directory.

**Comment by gnunn1** [comment]
You should have received a dialog that warned you about a VTE configuration issue, did it not appear for you?

https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue

**Comment by gnunn1** [comment]
No response from OP, closing issue.

**Comment by giray** [comment]
Hi ...

  At this point including the "fixes" in works as expected when splitting the terminal, but not when you start a new session

**Comment by gnunn1** [comment]
I just tested it and it's working fine for me, I think I fixed this last night as part of #260.

**Comment by giray** [comment]
just did a pull and on master its not fixed.  Terminix About says 0.581.

Splitting works .. current is inherited.  While new session/tab starts at $HOME

**Comment by gnunn1** [comment]
I think I've been completely mis-understanding the issue. I've been so focused on the directory issues when launching Terminix I've been thinking this issue is referring to the New Instance option. I think what you are actually getting at is that you expect when you click the New Session button it should inherit the directory of the currently focused terminal, is that correct?

I'm re-opening this issue and I'll take care of it, my apologies for the confusion and thanks for your patience.

**Comment by giray** [comment]
no worries! :)

love the end product!

**Comment by giray** [comment]
confirmed fixed!  thx
