### ISSUE TITLE
Splitters are transparent depending on the gtk theme

### ISSUE THREAD

**Issue by golimpio** [gnunn1/terminix#319]
I've noticed that the splitters became transparent, depending on the gtk theme we use:
![transparent-splitters](https://cloud.githubusercontent.com/assets/138681/15166017/fcf0c720-175d-11e6-9b19-6819bea87f08.png)

Ambiance theme doesn't seem to have this issue, but others gtk themes have the same issue (e.g. Paper).

**Edit:** I have the same issue with Adwaita theme

Environment:
- Adapta gtk theme
- Ubuntu 16.04
- Gtk 3.18

**Comment by gnunn1** [comment]
Thanks, what version of Terminix are you using, is it the one from git?

**Comment by golimpio** [comment]
@gnunn1 Yes it is...I just pulled the latest one from git today.

**Comment by gnunn1** [comment]
Hmm, that's weird because I just tried it on 16.04 with Adapta and it looks fine to me as per the screenshot below. When you say you get the latest one from git today, you mean you did a ```git checkout``` and built it manually using ``dub build --build=release``` or do you mean you got the archive from the Releases section in git?

**Comment by gnunn1** [comment]
Here's what it looks like for me (with wide handle enabled in Preferences | Appearance):

![screenshot from 2016-05-10 18-05-49](https://cloud.githubusercontent.com/assets/9358238/15166259/54203e88-16da-11e6-89bb-77f3111fc183.png)

**Comment by golimpio** [comment]
Sorry, I should have been more specific:
```
git fetch
git pull
```

Running a `git status` I get:
```
On branch master
Your branch is up-to-date with 'origin/master'.
```

Then I ran: 
```
dub build --build=release` 
sudo ./install.sh
```

**Comment by golimpio** [comment]
It might be something specific to my setup then (I'm running Ubuntu 16.04/Unity).

**Comment by gnunn1** [comment]
I'm using Ubuntu 16.04 and Unity in my VM and I installed the latest Adapta theme from their PPA. In the Terminix Preference | Appearance tab, does not toggling the option to use Wide Handles make any difference? You should see the splitter grow in size when enabled and shrink when it is not.

**Comment by gnunn1** [comment]
OK I can replicate in Fedora 23 with Adwaita and enabling the wide handle option. Still works fine in Ubuntu though under Adapta but hopefully fix will cover both cases.

**Comment by golimpio** [comment]
Toggling the option to use Wide Handles work as expected, but even the normal handlers are transparent in my case.

I'm using the latest Adapta from git, this might be the problem then.

Also, I can see the same issue in Adwaita actually (my first report is wrong).

Ambience works fine.

**Comment by gnunn1** [comment]
I just checked in an update to the CSS which fixes it in Fedora 23, can you get the latest from git and run ```sudo install.sh``` again to update the CSS in the resource file and let me know how it goes.

**Comment by golimpio** [comment]
Now with the wide splitter I have:
![split-issue-wide](https://cloud.githubusercontent.com/assets/138681/15166641/54a34708-1764-11e6-97f8-eaf41a944711.png)

And with the normal one:
![split-issue-thin](https://cloud.githubusercontent.com/assets/138681/15166648/5ee2a100-1764-11e6-99dc-1707e21d9750.png)

**Comment by golimpio** [comment]
Adwaita seems to work fine now (I don't know how it looked before):
![split-adwaita](https://cloud.githubusercontent.com/assets/138681/15166711/d860f996-1764-11e6-9ea5-5138ed2d3618.png)

**Comment by gnunn1** [comment]
So transparency is fixed but the wide one on Adapta looks ugly, I can live with that for now. Are you OK with this?

BTW, this is a side effect of supporting transparent scrollbars, for the scrollbar to be transparent the whole background needs to be transparent which can cause problems with the panes on some themes.
I could make the transparent scrollbars an option but I much prefer the "just make it work" approach to making everything an option.

**Comment by golimpio** [comment]
Sorry, transparency issue is still there (I'm using the dark variant and the window behind Terminix is white).

But anyway, It's not really a big deal, I usually use the thin splitter and the thin splitter looks alright!

Thank you for your support!

**Comment by gnunn1** [comment]
OK thanks for the feedback, I'm going to leave this open and look into if there is an optimum way to address this, I have some thoughts but need some time to try some things. Wish I could duplicate your Adapta experience though, would make tweaking things much easier. If I make some changes for this, I'll update the bug report so you can test it.

**Comment by golimpio** [comment]
Sounds good to me...I think I have a different experience because I'm using the Adapta from GIT/master, it might be slightly different from the PPA.

**Comment by gnunn1** [comment]
Just a reminder note to myself, suspect the best solution is to add a CSS class that I used to have for any theme that the transparent scrollbar is not supported, otherwise I suspect trying to style the GTKPaned separator itself is going to lead to less then optimal results. For example, in Adapta with the wide handle there are two thin transparent strips even though the background is properly styled.

**Comment by gnunn1** [comment]
See #303 for more info on this change
