### ISSUE TITLE
Supporting VTE configuration with FISH shell

### ISSUE THREAD

**Issue by CrashyBang** [gnunn1/terminix#481]
I am trying to set up VTE based off these [instuctions](https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue) with [fish shell](https://fishshell.com/) however it is unsupported.

Has anyone managed this? I have tried using this [VTE rewrite for fish](https://github.com/fisherman/fish-vte).

I thought a potential solution may be to default to `bash` then after I am done `source`ing `vte.sh` execute/enter the `fish` shell?

Looking for suggestions/work-around's anyone has come up with?

Cheers.

**Comment by gnunn1** [comment]
I think this should already be working according to this fish bug report:

https://github.com/fish-shell/fish-shell/pull/973

When you split the terminal us it using the directory from the previous terminal or $HOME?

**Comment by gnunn1** [comment]
So I just tested fish and it works as expected for me. Are you using the stable version or the current master from git? I cleaned up some issues with the warning between stable and the current version so it's possible I've already fixed this.

**Comment by CrashyBang** [comment]
Ahh possibly not I will test as soon as I get Home.

Just out of curiosity will it still show this error even if fish is working? (Or will it detect fish and not show this?)

![onpaste 20160915-091956](https://cloud.githubusercontent.com/assets/2978850/18530461/b583ba92-7b25-11e6-9cba-10020fdb881f.png)

Cheers.

**Comment by gnunn1** [comment]
On my system running master with fish I do not see the error and things
work as expected. Hopefully in your case things are actually working and
you are only seeing the dialog due too a bug in my case. In this case you
can simply disable by selecting the do not show me this again checkbox on
the dialog.

Gerald

**Comment by CrashyBang** [comment]
Hey @gnunn1,

Will test with latest fish tonight, that is cool if it is a bug in terminix it was just a little confusing trying to figure out what I was doing wrong :L if there is anything I can do to help track it down let me :).

Cheers.

**Comment by CrashyBang** [comment]
Hey @gnunn1,

With stable master build and new FISH everything seems to be working :).

Cheers.

**Comment by gnunn1** [comment]
Awesome, thanks for testing!
