### ISSUE TITLE
Quake mode focus

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#497]
See http://sendvid.com/s4vcwvaw

In the video, first I'm clicking on the desktop and then hitting the hotkey to show Terminix in quake mode.  Terminix focuses without issue.  After closing Terminix by hitting the hotkey again I click in the Firefox window and again hit the hotkey.  This time the Terminix window isn't focused.

**Comment by gnunn1** [comment]
@alexwhitman I had that issue in Gnome Shell at one point and it seemed to get sorted out with some tweaks to the present/show/focus order of things. I'll have a look in more detail on Ubuntu in the next day or two.

**Comment by gnunn1** [comment]
I can reproduce in my Ubuntu 16.10 VM but it seems strangely tied to firefox. If I click on a different window say Nautilus or gedit instead of firefox there is no issue.

**Comment by gnunn1** [comment]
I've created a fix for this based on some similar code I see in xfce4-terminal. @alexwhitman can you test this and let me know if it fixes the issue for you please.

If this fixes the issue, I'll drop a line asking the xfce guys for permission to re-license it under Mozilla instead of GPL.

**Comment by alexwhitman** [comment]
Seems to be working fine at the moment.

It does seem to have introduced an odd issue, but I'm not sure how as none of the related code was touched as far as I can tell.  If you uncheck the "Close window when last session is closed" option and then open a new Terminix window, hit Ctrl+D and see a new session is opened.  On my machine the caret is an outlined black box rather than a solid white box, however, the terminal still has focus and I can type without a problem.  Clicking in the window doesn't change the caret state.  This happens in both a quake mode window and normal windows.

**Comment by gnunn1** [comment]
I can reproduce it, I tried one workaround of spawning the createSession later when idle in case it was related to being in the close event but still get the same behavior. One unrelated thing I noticed about this setting, when it's active shouldn't we allow the session close action to be enabled when there is only one session?

Getting back to the issue, I don't think it's related to the fix for the quake focus issue, that code is only executed when in quake mode, see these lines in application.d:

```
            if (cp.quake) {
                AppWindow qw = getQuakeWindow();
                if (qw !is null) {
                    if (qw.getVisible) {
                        qw.hide();
                    } else {
                        qw.show();
                        qw.present();
                        qw.getActiveTerminal().focusTerminal();
                        activateWindow(qw);
                    }
                    return 0;
                }
```

**Comment by gnunn1** [comment]
I see that focus issue has been reported in Ubuntu however it is reported as being fixed in 3.18:

https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/890784

**Comment by alexwhitman** [comment]
I did a quick roll back to an earlier commit and the issue is still present so not related to this.  Maybe something changed in an Ubuntu update.

**Comment by gnunn1** [comment]
It happens on my Arch Linux as well so not just Ubuntu related. I've tried a few things to fix it but no luck so far. I may need to revert this feature if I can't resolve the issue.

**Comment by alexwhitman** [comment]
I wouldn't see it as a reason to revert the change.  It's cosmetic more than anything and fixes itself when switching to another session and then back again.

**Comment by gnunn1** [comment]
Yeah that might be a bit extreme, I'm just trying to short circuit the inevitable bug reports from users. As well, I didn't realize this would only be useful when hitting ctrl-d, I thought the session close option would be active as well. Thus this option seems to cover a very narrow use case, is it worth keeping when it's not a 100%?
