### ISSUE TITLE
Quake height and width adjustments have no effect

### ISSUE THREAD

**Issue by kam3k** [gnunn1/terminix#586]
I'm running Debian Testing with GNOME Shell 3.22.2 and Terminix 1.3.0. No matter what I set the quake height and width percent to, the quake window is always maximized (i.e., takes up my full screen).

**Comment by gnunn1** [comment]
Can you try with the current release (1.3.5) and see if it works as I've fixed a number of quake issues.

**Comment by gnunn1** [comment]
Also, are you using X11 or Wayland?

**Comment by kam3k** [comment]
I am using X11. I tried the latest release, and the problem persists. By the way, I got myself confused because after installing 1.35 the About dialog still states the version is 1.30.

**Comment by zeten30** [comment]
Hi, I'm experiencing the same thing with 1.3.5, but only under Wayland/Gnome Shell 3.22/Fedora 25. Secondary effect is that width slider is not visible on Quake tab in preferences. Window seems to start maximised, it can be resized using shortcut, but it doesn't survive next visibility toggle.
Works perfect under X11.

**Comment by gnunn1** [comment]
@zeten30 Unfortunately there are significant differences in quake mode between X11 and Wayland, Wayland has a number of limitations that are difficult to work around. This is why I was originally very reluctant to implement it. Changing the width isn't supported under Wayland because as soon as you do the WM starts positioning the window where it thinks it should go instead of at the top as requested. 

Having said that, good to know that in Fedora 25 you are having the same issue with the window going full height even if it's under Wayland. I'll have a look at this in more detail over the next few days.

**Comment by gnunn1** [comment]
Actually, just having a thought to myself, I wonder if it be worth looking at forcing terminix to run as an X11 window under Wayland when quake mode is active.

**Comment by zeten30** [comment]
@gnunn1 I know that making things working under Wayland might be tricky. That's why I'm still using X11 instead. Forcing XWayland for quake mode can be be a workaround. 

@kam3k In my case, after experimenting with Wayland, I had to restore - under X11 - window state from maximized to normal via Super + down arrow shortcut. Eventually set gsettings values from terminal. No issues with quake mode when user was not playing with Wayland at all.

**Comment by zeten30** [comment]
I've tested quake mode under Wayland, but forcing x11 backend - 'GDK_BACKEND=x11 terminix -q'. It works as expected. Terminal is showing with proper width.

**Comment by gnunn1** [comment]
@zeten30 Thanks for trying that out, could be an interesting option for folks.

@kam3k I'm hoping to work on this more in the next few days, I'm a bit distracted at the moment with another issue which has a higher priority. I did try installing Debian Stretch in VirtualBox, unfortunately it doesn't boot after installation but just constantly flashes text about intel rapi. Need to look into this some more ince I get the memory leak issue sorted, thanks for your patience.

**Comment by kam3k** [comment]
@gnunn1 Thanks for your efforts! Let me know if there is anything you'd like me to test on my machine.

**Comment by gnunn1** [comment]
@kam3k So I got Debian stretch going in virtualbox, trick was to install lightdm, and attempted to reproduce this with no luck, it worked perfectly fine for me. Do you have anything unusual installed on your system in terms of window managers, gnome-shell extensions, etc that could interfere with things?

**Comment by kam3k** [comment]
@gnunn1 I am now noticing some very odd behavior. For example:

- I've set a the profile of the quake window to be different than my "main" terminix window (I have one window I keep open all the time, and I use the quake window as a "scratch" terminal). Sometimes the profile of the quake window resets to the same as my other open window, sometimes it doesn't.

- The height and width sporadically started working sometimes, and other times it just opens fully maximized.

- Sometimes the origin of the quake window changes (when it isn't maximized). Sometimes it is fixed to top centre, sometimes it is fixed to the top left, for example.

I only have one gnome-shell extension enabled ([Maximus NG](https://extensions.gnome.org/extension/1026/maximus-ng/)), although disabling it had no effect on the behaviour of Terminix. Other than that, this is a pretty lean, somewhat fresh install of Debian.

**Comment by gnunn1** [comment]
How are you setting the profile for the quake window, are you passing it in with the --profile command switch along with --quake? If so I wonder if you are hitting an issue with that as I don't believe I tested this explicitly.

If you are doing this, try using just the --quake switch by itself and see if you get more consistent behavior.

**Comment by kam3k** [comment]
I just pass the --quake switch. To set the profile, I right click on the quake window when it is open and choose the profile from the context menu.

**Comment by gnunn1** [comment]
Well I'm getting a bit stumped, if you are up for it I'll build you a debug version from master that you can try that includes tracing. Hopefully it will shed some light on what is going on.

**Comment by kam3k** [comment]
No, I'll spare you the trouble. I don't mind just using the window full screen for the time being. Seeing as you cannot reproduce it, it may just be something peculiar with my set up. Thanks for your time, and for your terrific application. Feel free to close this issue.

**Comment by gnunn1** [comment]
Ok thanks, if you want to revisit the issue just reopen it.
