### ISSUE TITLE
Negative x/y offsets do not work

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#655]
Running `terminix --geometry=80x24-10-10` doesn't work as expected - the window bottom right corner should be located 10 pixels to the left from the right border of the screen and 10 pixels up from the bottom border.

**Comment by gnunn1** [comment]
I've fixed this so that geometry is interpreted correctly and it attempts to move the window. However under the Gnome window manager it won't let me position the window negatively. Can you test it on yours and test that it works.

**Comment by f2404** [comment]
Nope, still not working for me under Xfce.
But, now it's a bit different: before your change, the window used to open in the middle of the screen when using negative offsets - now it's opening in top left corner.

**Comment by gnunn1** [comment]
II think this is just a limitation of the window managers, I'm definitely moving the window to the right coordinates. is there an application where this does work? I've tried both gnome-terminal and xfce4-terminal neither of which handles the negative offsets at all as far as I can tell.

**Comment by f2404** [comment]
Both gnome-terminal and xfce4-terminal are working fine with negative offsets for me. Also, there's xterm which is also working fine and can be taken as a reference here.

**Comment by gnunn1** [comment]
On gnome 3.22 nothing works with the negative offset, xterm gives the same behavior as the other two.

```
xterm -geometry 80x24-50-50
```

**Comment by gnunn1** [comment]
Unfortunately not at this time, I don't have those environments installed and I don't officially support either one. If I had more time I'd look into it but I'm hip deep into some GtkD and VTE items right now. If you want to debug it yourself, this is where the code that does the move resides:

https://github.com/gnunn1/terminix/blob/master/source/gx/terminix/appwindow.d#L1024

**Comment by f2404** [comment]
`move(terminix.getGlobalOverrides().x, terminix.getGlobalOverrides().y);`
The problem is that this command parameters are coordinates of the top left corner of the window. Thus, provided with negative `x` and `y` values, it will move the window to top left corner of the screen.
Per X standard, if `x` (or `y`) is negative, it represents a distance from right (or bottom) border of the screen. So, `--geometry=80x24-10-10` should result in `move(screen.width-window.width-10, screen.height-window.height-10);`.

**Comment by gnunn1** [comment]
Suddenly it all makes sense. Thanks, I wasn't aware of that about the x11 spec, I'll fix this one shortly.

**Comment by f2404** [comment]
Please see https://www.x.org/archive/X11R6.7.0/doc/X.7.html#sect6
